[default]
optimizer = true
optimizer_runs = 2000000
remappings = [
    "ds-test=lib/ds-test/src/",
    "solmate=lib/solmate/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

[ci]
verbosity = 4